services:
  guestbook:
    image: docker.io/zekro/demo-guestbook
    environment:
      GUESTBOOK_ADDRESS: ":8080"
      GUESTBOOK_STORAGE_DIR: "/data"
      GUESTBOOK_SIMULATOR_ENABLED: "true"
      GUESTBOOK_SIMULATOR_INTERVAL: "5s"
    ports:
      - "8080:8080"
    volumes:
      - data:/data
    deploy:
      replicas: 2
      update_config:
        order: start-first
      restart_policy:
        condition: on-failure

volumes:
  data:
    driver_opts:
      type: nfs
      o: "addr=${NFS_ADDRESS?},nfsvers=4,rw,soft"
      device: ":${NFS_SHARE?}/guestbook"
